sonar.projectKey=ricardoliveira5ro_foot-play
sonar.organization=ricardoliveira5ro
sonar.sources=frontend/src,backend/src
sonar.tests=backend/src/__tests__
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
sonar.exclusions=backend/src/__tests__/**,backend/src/generated/**,frontend/src/**/*.test.*,**/node_modules/**
sonar.sourceEncoding=UTF-8
